/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
/**
 *
 * @author Joseg
 */
public class PartidosPoliticos extends javax.swing.JFrame {

    /**
     * Creates new form PartidosPoliticos
     */
    public PartidosPoliticos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ingresarNombresCandidatos = new javax.swing.JButton();
        generarVotos = new javax.swing.JButton();
        calcularGanador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVotosTextArea = new javax.swing.JTextArea();
        calcularMenosVotado = new javax.swing.JButton();
        mostrarTablaVotos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Partidos Políticos");

        ingresarNombresCandidatos.setText("Ingresar Candidatos");
        ingresarNombresCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarNombresCandidatosActionPerformed(evt);
            }
        });

        generarVotos.setText("Generar votos");
        generarVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarVotosActionPerformed(evt);
            }
        });

        calcularGanador.setText("Calcular ganador");
        calcularGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularGanadorActionPerformed(evt);
            }
        });

        tablaVotosTextArea.setColumns(20);
        tablaVotosTextArea.setRows(5);
        jScrollPane1.setViewportView(tablaVotosTextArea);

        calcularMenosVotado.setText("Calcular menos votado");
        calcularMenosVotado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularMenosVotadoActionPerformed(evt);
            }
        });

        mostrarTablaVotos.setText("Mostrar votos");
        mostrarTablaVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTablaVotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ingresarNombresCandidatos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generarVotos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mostrarTablaVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calcularGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calcularMenosVotado)
                                .addGap(0, 33, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarNombresCandidatos)
                    .addComponent(generarVotos)
                    .addComponent(calcularGanador)
                    .addComponent(calcularMenosVotado))
                .addGap(18, 18, 18)
                .addComponent(mostrarTablaVotos)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int[][] votos;
    String[] nombresCandidatos;
    int NUM_RONDAS = 5;
    private void ingresarNombresCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarNombresCandidatosActionPerformed
        nombresCandidatos = new String[10];
        for (int i = 0; i < 10; i++) {
            nombresCandidatos[i] = JOptionPane.showInputDialog("Ingrese el nombre del Candidato " + (i + 1) + ":");
        }
    }//GEN-LAST:event_ingresarNombresCandidatosActionPerformed

    private void calcularMenosVotadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularMenosVotadoActionPerformed
         int menosVotado = 0;
        int totalVotosMenosVotado = Integer.MAX_VALUE;
        for (int i = 0; i < nombresCandidatos.length; i++) {
            int totalVotosCandidato = 0;
            for (int j = 0; j < 5; j++) {
                totalVotosCandidato += votos[i][j];
            }
            if (totalVotosCandidato < totalVotosMenosVotado) {
                menosVotado = i;
                totalVotosMenosVotado = totalVotosCandidato;
            }
        }

        JOptionPane.showMessageDialog(this, "El candidato menos votado es: " + nombresCandidatos[menosVotado]);
    }//GEN-LAST:event_calcularMenosVotadoActionPerformed

    private void calcularGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularGanadorActionPerformed
       int totalVotos[] = new int[nombresCandidatos.length];
        for (int i = 0; i < nombresCandidatos.length; i++) {
            for (int j = 0; j < 5; j++) {
                totalVotos[i] += votos[i][j];
            }
        }

        int ganador = 0;
        for (int i = 1; i < nombresCandidatos.length; i++) {
            if (totalVotos[i] > totalVotos[ganador]) {
                ganador = i;
            }
        }

        JOptionPane.showMessageDialog(this, "El ganador de las elecciones es: " + nombresCandidatos[ganador]);
    }//GEN-LAST:event_calcularGanadorActionPerformed

    private void mostrarTablaVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTablaVotosActionPerformed
       StringBuilder tablaVotos = new StringBuilder("Tabla de Votos:\n");
        for (int i = 0; i < nombresCandidatos.length; i++) {
            tablaVotos.append(nombresCandidatos[i]).append(": ");
            for (int j = 0; j < 5; j++) {
                tablaVotos.append(votos[i][j]).append(" ");
            }
            tablaVotos.append("\n");
        }
        tablaVotosTextArea.setText(tablaVotos.toString());
    }//GEN-LAST:event_mostrarTablaVotosActionPerformed

    private void generarVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarVotosActionPerformed
      votos = new int[nombresCandidatos.length][5];
        Random random = new Random();

        for (int i = 0; i < nombresCandidatos.length; i++) {
            for (int j = 0; j < 5; j++) {
                votos[i][j] = random.nextInt(50 + 1); // Número máximo de votos (50)
            }
        }
    }//GEN-LAST:event_generarVotosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartidosPoliticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartidosPoliticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartidosPoliticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartidosPoliticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartidosPoliticos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularGanador;
    private javax.swing.JButton calcularMenosVotado;
    private javax.swing.JButton generarVotos;
    private javax.swing.JButton ingresarNombresCandidatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarTablaVotos;
    private javax.swing.JTextArea tablaVotosTextArea;
    // End of variables declaration//GEN-END:variables
}
